import dotenv from 'dotenv';
import fs from 'fs';
import path from 'path';
import { generateVideoVeoAiFree } from '../services/veoaifree';

dotenv.config({ path: path.join(process.cwd(), '.env') });

function parseArgs() {
  const args = process.argv.slice(2);
  const out: { prompt?: string; duration?: number } = {};

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (arg === '--prompt' && args[i + 1]) {
      out.prompt = args[i + 1];
      i++;
    } else if (arg === '--duration' && args[i + 1]) {
      const parsed = Number(args[i + 1]);
      if (!Number.isNaN(parsed)) out.duration = parsed;
      i++;
    }
  }

  return out;
}

async function main() {
  const { prompt: promptArg, duration: durationArg } = parseArgs();
  const prompt =
    promptArg ||
    process.env.VEO_TEST_PROMPT ||
    'A cinematic office scene with a developer coding at multiple monitors, natural daylight, realistic motion';
  const duration = durationArg || Number(process.env.VEO_TEST_DURATION || 5);

  const tmpDir = path.join(process.cwd(), 'uploads', 'tmp');
  fs.mkdirSync(tmpDir, { recursive: true });

  console.log('--- VEOAIFREE Puppeteer Smoke Test ---');
  console.log(`Prompt   : ${prompt}`);
  console.log(`Duration : ${duration}s`);
  console.log(`Tmp Dir  : ${tmpDir}`);

  const startedAt = Date.now();
  const result = await generateVideoVeoAiFree(prompt, duration, (step, progress) => {
    const pct = Math.round(progress * 100);
    console.log(`[${pct}%] ${step}`);
  });

  if (!result?.localPath) {
    console.error('FAIL: No video generated by VEOAIFREE/Puppeteer.');
    process.exit(1);
  }

  if (!fs.existsSync(result.localPath)) {
    console.error(`FAIL: Generation reported success, but file does not exist: ${result.localPath}`);
    process.exit(1);
  }

  const stat = fs.statSync(result.localPath);
  const elapsedSec = ((Date.now() - startedAt) / 1000).toFixed(1);
  console.log('SUCCESS: Video generated.');
  console.log(`File     : ${result.localPath}`);
  console.log(`Size     : ${(stat.size / (1024 * 1024)).toFixed(2)} MB`);
  console.log(`Elapsed  : ${elapsedSec}s`);
}

main().catch((err: any) => {
  console.error('FAIL: Smoke test crashed.');
  console.error(err?.stack || err?.message || err);
  process.exit(1);
});
